= Dockerfile

:project-name: tutorial-app
:quarkus-version: 2.3.0.Final

A Dockerfile is where you'll estabilish the definitions used to build a container image. It uses three main keywords/commands:

* FROM: where you'll inform the base image used to build your own image
* ADD: where you'll add resources (files) to your image
* CMD: where you'll inform how to start the application

[TIP]
====
Sometimes people ask when to use ADD and when to use COPY. Both of them can be used to copy files from the source to destination, but:

* COPY: Simple copy of local files into the container
* ADD: Will also extract local tar files and supports remote URL. 
It is less obvious thus it is preferable to use COPY unless you specifically need these features
====

== Creating an application to be containerized

Let's first create a simple Java application so we can containerize it.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn "io.quarkus:quarkus-maven-plugin:{quarkus-version}:create" \
  -DprojectGroupId="com.redhat.developers" \
  -DprojectArtifactId="{project-name}" \
  -DprojectVersion="1.0-SNAPSHOT" \
  -DclassName="HelloResource" \
  -Dpath="hello"
cd {project-name}
----

IMPORTANT: All the remaining parts of this tutorial assume that you'll be working inside the project folder that was just created. In this case, `{project-name}`.

To let this application be ready to be distributed, let's package it:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn package
----


== Building a Dockerfile

Create a file named Dockerfile.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF >Dockerfile
FROM registry.access.redhat.com/ubi8/openjdk-11

ADD target/quarkus-app/lib/ /deployments/lib/
ADD target/quarkus-app/quarkus-run.jar /deployments/app.jar
ADD target/quarkus-app/app/ /deployments/app/
ADD target/quarkus-app/quarkus/ /deployments/quarkus/

CMD ["java", "-jar", "/deployments/app.jar"]
EOF
----

