= Dockerfile

:project-name: tutorial-app
:quarkus-version: 1.8.2.Final

A Dockerfile is where you'll estabilish the definitions used to build a container image. It uses three main keywords/commands:

* FROM: where you'll inform the base image used to build your own image
* ADD: where you'll add resources (files) to your image
* CMD: where you'll inform how to start the application

[TIP]
====
Sometimes people ask when to use ADD and when to use COPY. Both of them can be used to copy files from the source to destination, but:

* ADD: The source can only be the host
* COPY: The source can be the host or a remote URL 
====

== Creating an application to be containerized

Let's first create an simple Java application so we can containerize it.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn "io.quarkus:quarkus-maven-plugin:{quarkus-version}:create" \
  -DprojectGroupId="com.redhat.developers" \
  -DprojectArtifactId="{project-name}" \
  -DprojectVersion="1.0-SNAPSHOT" \
  -DclassName="HelloResource" \
  -Dpath="hello"
cd {project-name}
----

IMPORTANT: All the remaining parts of this tutorial assume that you'll be working inside the project folder that was just created. In this case, `{project-name}`.

To let this application ready to be distributed, let's package it:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn package
----


== Building a Dockerfile

Create a file named Dockerfile.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF >Dockerfile
FROM registry.access.redhat.com/ubi8/openjdk-11

ADD target/lib/* /deployments/lib/
ADD target/*-runner.jar /deployments/app.jar

CMD ["java", "-jar", "/deployments/app.jar"]
EOF
----

