[[requirements]]
= Setup
include::_attributes.adoc[]

== Required Tools

The following tools are required for running the exercises in this tutorial. You'll need to have them installed and configured before you get started with any of the tutorial chapters.

TIP: By default, the commands in this tutorial are using podman, but you can use `docker` instead of `podman` throughout the tutorial's instructions as the commands will be identical (eg. `podman run` will be the same as `docker run`). The advantage of Podman is that it is 100% Free Open Source and does not need to run with elevated privileges.

[options="header"]
|===
| **Tool** | **macOS** | **Fedora** |**Windows**

| **Podman Desktop**
| https://podman-desktop.io/downloads[Podman Desktop for Mac, window="_blank"]
| https://podman-desktop.io/downloads[Podman Desktop for Linux, window="_blank"]
| https://podman-desktop.io/downloads[Podman Desktop for Windows, window="_blank"]

| **Java 21**
| https://adoptium.net/installation/
| https://adoptium.net/installation/ alternatively: 

`dnf install java-21-openjdk-devel`
| https://adoptium.net/installation/ (Make sure you set the `JAVA_HOME` environment variable and add `%JAVA_HOME%\bin` to your `PATH`)

| **Apache Maven 3.9.9+**
| `brew install maven`
| `dnf install maven`
| https://maven.apache.org/download.cgi[Windows] (Make sure you set the `MAVEN_HOME` environment variable and add `%MAVEN_HOME%\bin` to your `PATH`)

|===

== Optional Tools

The following tools are optional, feel free to replace with your own preferred ones.


[options="header"]
|===
|**Tool**|**macOS**|**Fedora**|**Windows**

| **Visual Studio Code**
3+| Open https://code.visualstudio.com/download[Visual Studio Code download page, window="_blank"] and follow the installation instructions related to your operating system

| **curl**
| `brew install curl`
| `dnf install curl`
| https://curl.se/windows/[Windows]

|===

== Quay.io Account

**Quay.io** is a **container image registry** service, similar to _Docker Hub_, which is fully managed by Red Hat. It provides a centralized, secure place for users and organizations to store, build, and distribute their OCI (Open Container Initiative) container images.

NOTE: If you already have a _Quay.io_ account or a _Docker Hub_ account, you can skip this section.

=== Creating a Quay.io Account

A Quay.io account is typically linked to a **Red Hat account**.

.  *Navigate to Quay.io*: Go to the https://quay.io/[Quay.io] website.
.  *Sign In*: Look for a `Sign In` button in the top right corner and *click on* it. Since Quay.io is part of Red Hat's ecosystem, you'll be directed to use your Red Hat credentials.
      * If you *already have a Red Hat account*, sign in with those credentials.
      * If you *do not have a Red Hat account*, select `Register for a Red Hat account` and follow the prompts to register for a new Red Hat account.
.  *Confirm Username*: Upon your first login to Quay.io using your Red Hat credentials, you may be redirected to a page to *confirm your username*. This username will serve as your *namespace* (e.g., `quay.io/<your-username>/<repo-name>`) in the container registry.

=== Creating a Repository

A repository is a storage location for your container images and related artifacts: think of it as a folder or directory for a specific containerized application or component.

. *Log In*: Sign in to your Quay.io account.
. Make sure that you are in the _Repositories_ tab: On the left side of your screen, look for a *+* icon followed by *Create New Repository* label and click on it.
. *Insert a name for your repository*: e.g., `my-first-app`.
. Optionally add a repository description.
. Choose the _Repository Visibility_:
      * *Public*: Anyone can see and pull from this repository. You choose who can push.
      * *Private*: You choose who can see, pull and push from/to this repository.
. For this tutorial purposes, leave the initialization option set to `(Empty repository)`.
. *Create*: Click the *Create Repository* button. The repository will now appear in your list, ready to receive images.

=== Creating a robot account

In order to log in with the `podman` command line, you will need a robot account, here is how to create it:

. Once you have logged in, in the top right corner click on your username and *navigate* to the _Account Settings_ page.
. In the left vertical menu select the *Robot Accounts* icon to open the releated tab.
. Click on the *Create Robot Account* button.
. Enter a name for the robot account and click on the *Create* button.
. The next screen will propose you to *add permissions* to the robot account. You can choose to add permissions to a specific repository or to all repositories.
  .. Make sure to select the *Write* permission to use it for pushing images to the repository.
  .. Click on the *Add permissions* button.
. The robot account will now appear in your list, ready to be used.

NOTE: The robot account takes the following format: `<username>+<robot-account-name>`.
